[project]
name = "py-foundry-ontology"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "neo4j==5.28.2",
    "pandas==2.3.2",
    "sqlalchemy==2.0.43",
]
